apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: stern-crb
subjects:
- kind: ServiceAccount
  name: stern-admin
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: stern-cr
  apiGroup: rbac.authorization.k8s.io
