apiVersion: v1
kind: Service
metadata:
  labels:
    {{ toYaml .Values.labels }}
  name: cloudflare-operator-controller-manager-metrics-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    {{ toYaml .Values.labels }}